services:
  - type: web
    name: iot-chamber-backend
    runtime: node
    rootDir: Vanguard_Tools_Online/API
    buildCommand: npm install
    startCommand: node server_mirna.js
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
        placeholder: "Masukkan Host DB Aiven Anda"
      - key: DB_PORT
        sync: false
        placeholder: "Masukkan Port DB Aiven (misal: 12345)"
      - key: DB_USER
        sync: false
        value: "avnadmin"
      - key: DB_PASSWORD
        sync: false
        placeholder: "Masukkan Password DB Aiven"
      - key: DB_NAME
        sync: false
        value: "defaultdb"
